### Get all customers
GET http://localhost:3000/customers

### Get customer by ID
GET http://localhost:3000/customers/1

### Create new customer
POST http://localhost:3000/customers
Content-Type: application/json

{
  "email": "something@something.ss"
}

### Get all orders
GET http://localhost:3000/orders


### Get order by ID
GET http://localhost:3000/orders/ORD-123-2018


### Get all orders by customer email
POST http://localhost:3000/orders/filter
Content-Type: application/json

{
  "email": "test@test.tt"
}

### Create new order
POST http://localhost:3000/orders
Content-Type: application/json

{
  "orderNumber": "something",
  "trackingNumber": "1231233222",
  "courier": "",
  "street": "",
  "zipCode": 1111,
  "city":"",
  "destinationCountryIso3": "",
  "email":"test@test.tt",
  "articleNumber": "",
  "articleImageUrl":"",
  "quantity": 2,
  "productName":""
}

### Get all checkpoints
GET http://localhost:3000/checkpoints

### Get all checkpoints by order_number
GET http://localhost:3000/checkpoints/something

### Create checkpoint
POST http://localhost:3000/checkpoints
Content-Type: application/json

{
  "orderNumber": "something",
  "trackingNumber": "123123222232",
  "location":"",
  "status": "status",
  "statusText":"some status text",
  "statusDetail": "some status detaied version",
  "timestamp": 16940961423

}